# Generated by Django 2.2.5 on 2021-08-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Login', '0003_delete_employeedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('lic_no', models.CharField(max_length=300, verbose_name='License Number')),
                ('address', models.CharField(max_length=300, verbose_name='Company Headquarter Address')),
                ('cont_num', models.CharField(max_length=264, verbose_name='Company Contact Information')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(max_length=300, verbose_name='Company Description')),
                ('ph_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_employee', to='App_Login.Employee')),
                ('ph_manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_manager', to='App_Login.Manager')),
                ('pharmacy_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='App_Login.Admin')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Serial Number')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Medicine Name')),
                ('m_type', models.CharField(max_length=300, null=True, verbose_name='Which type of Medicine')),
                ('des', models.TextField(max_length=500, null=True, verbose_name='Medicine Description')),
                ('b_no', models.CharField(max_length=100, null=True, verbose_name='Batch No')),
                ('s_no', models.CharField(max_length=100, null=True, verbose_name='Shelf No or Rack No')),
                ('mfg_date', models.DateField(verbose_name='Manufacture Date')),
                ('expire_date', models.DateField(verbose_name='Expire Date')),
                ('dar_no', models.CharField(max_length=300, null=True, verbose_name='Combination of Drag Administration Number')),
                ('mfg_Lic', models.CharField(max_length=300, null=True, verbose_name='Manufacturing Licence Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('received_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('buy_price', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_medicine', to='App_medicine.Company')),
                ('ph_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_employee', to='App_Login.Employee')),
                ('ph_manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_manager', to='App_Login.Manager')),
                ('pharmacy_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_admin', to='App_Login.Admin')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_received', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_medicine.MedicineProduct')),
                ('ph_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_employee', to='App_Login.Employee')),
                ('ph_manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_manager', to='App_Login.Manager')),
                ('pharmacy_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_admin', to='App_Login.Admin')),
            ],
        ),
    ]
