# Generated by Django 2.2.5 on 2021-08-02 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ph_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_employee', to='App_Login.Employee'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ph_manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_manager', to='App_Login.Manager'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pharmacy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='App_Login.Admin'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicineproduct',
            name='ph_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_employee', to='App_Login.Employee'),
        ),
        migrations.AlterField(
            model_name='medicineproduct',
            name='ph_manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_manager', to='App_Login.Manager'),
        ),
        migrations.AlterField(
            model_name='medicineproduct',
            name='pharmacy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_admin', to='App_Login.Admin'),
        ),
        migrations.AlterField(
            model_name='medicineproduct',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='ph_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_employee', to='App_Login.Employee'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='ph_manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_manager', to='App_Login.Manager'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pharmacy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_admin', to='App_Login.Admin'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
