# Generated by Django 2.2.5 on 2021-07-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_employeedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
    ]
